# Generated by Django 4.0.2 on 2023-11-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='type',
            new_name='ride_type',
        ),
    ]
