# Generated by Django 4.0.2 on 2022-09-18 02:31

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path", "0001_initial"),
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="id",
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ride",
            name="path",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="path.path"
            ),
        ),
    ]
