# Generated by Django 4.0.2 on 2022-09-21 21:41

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path", "0001_initial"),
        ("ride", "0002_ride_id_alter_ride_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="path.path"
            ),
        ),
    ]
