# Generated by Django 4.0.2 on 2022-09-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0002_alter_ride_id"),
        ("ride", "0003_alter_ride_path"),
    ]

    operations = []
