# Generated by Django 4.0.2 on 2023-04-19 01:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_name", models.CharField(max_length=200)),
                (
                    "question_placeholder",
                    models.CharField(default="", max_length=200, null=True),
                ),
            ],
        ),
    ]
