# Generated by Django 4.0.2 on 2023-10-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, default=None, to='person.Person'),
        ),
    ]
