# Generated by Django 4.0.2 on 2023-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fcm_registration_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
