# Generated by Django 4.0.2 on 2023-03-14 17:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
        ("person", "0002_person_profile_pic_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="prompt_answers",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="prompt_questions",
            field=models.ManyToManyField(blank=True, default=None, to="prompts.Prompt"),
        ),
    ]
