# Generated by Django 4.0.2 on 2023-04-19 01:45

import datetime

from django.db import migrations
from django.db import models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=None, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 19, 1, 45, 34, 203037, tzinfo=utc
                        )
                    ),
                ),
                (
                    "approvee",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvee",
                        to="person.person",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approver",
                        to="person.person",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ride.ride"
                    ),
                ),
            ],
        ),
    ]
