# Generated by Django 4.0.2 on 2022-09-22 17:25

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 22, 17, 25, 41, 389032)
            ),
        ),
    ]
