# Generated by Django 4.0.2 on 2022-09-21 21:52

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ride", "0001_initial"),
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ride.ride"
            ),
        ),
    ]
