# Generated by Django 4.0.2 on 2023-10-05 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 18, 24, 37, 364420, tzinfo=utc)),
        ),
    ]
