# Generated by Django 4.0.2 on 2023-11-08 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 22, 56, 23, 143367, tzinfo=utc)),
        ),
    ]
