# Generated by Django 4.0.2 on 2022-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_initial"),
        ("request", "0002_request_timestamp"),
    ]

    operations = []
