# Generated by Django 4.0.2 on 2022-11-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_initial"),
        ("request", "0002_request_timestamp"),
    ]

    operations = []
