# Generated by Django 4.0.2 on 2023-11-12 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 17, 34, 6, 28835, tzinfo=utc)),
        ),
    ]
