# Generated by Django 4.0.2 on 2023-03-14 17:33

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_merge_0002_initial_0002_request_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 17, 33, 40, 593218, tzinfo=utc)
            ),
        ),
    ]
