# Generated by Django 4.0.2 on 2023-03-19 16:57

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0004_alter_request_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 19, 16, 57, 2, 262226, tzinfo=utc)
            ),
        ),
    ]
