# Generated by Django 4.0.2 on 2022-04-21 21:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location_place_id", models.TextField()),
                ("start_location_name", models.TextField()),
                ("end_location_place_id", models.TextField()),
                ("end_location_name", models.TextField()),
            ],
        ),
    ]
