# Generated by Django 4.0.2 on 2023-03-19 16:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("path", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="end_lat",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="path",
            name="end_lng",
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="path",
            name="start_lat",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="path",
            name="start_lng",
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
